import { ROLES, type UserRole } from '../types';

export const PERMISSIONS = {
  VIEW_SERVICES: 'VIEW_SERVICES', CREATE_APPLICATION: 'CREATE_APPLICATION', VIEW_OWN_APPLICATIONS: 'VIEW_OWN_APPLICATIONS',
  REVIEW_APPLICATIONS: 'REVIEW_APPLICATIONS', VIEW_GRIEVANCES: 'VIEW_GRIEVANCES', VIEW_DEPARTMENT_ANALYTICS: 'VIEW_DEPARTMENT_ANALYTICS', VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_PLATFORM_ANALYTICS: 'VIEW_PLATFORM_ANALYTICS', MANAGE_USERS: 'MANAGE_USERS', MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS', MANAGE_SERVICES: 'MANAGE_SERVICES', VIEW_SYSTEM_ACTIVITY: 'VIEW_SYSTEM_ACTIVITY',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const rolePermissions: Record<UserRole, readonly Permission[]> = {
  [ROLES.USER]: [PERMISSIONS.VIEW_SERVICES, PERMISSIONS.CREATE_APPLICATION, PERMISSIONS.VIEW_OWN_APPLICATIONS],
  [ROLES.DEPARTMENT_OFFICER]: [PERMISSIONS.VIEW_SERVICES, PERMISSIONS.REVIEW_APPLICATIONS, PERMISSIONS.VIEW_GRIEVANCES, PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS, PERMISSIONS.VIEW_REPORTS],
  [ROLES.ADMIN]: [PERMISSIONS.VIEW_PLATFORM_ANALYTICS, PERMISSIONS.MANAGE_USERS, PERMISSIONS.MANAGE_DEPARTMENTS, PERMISSIONS.MANAGE_SERVICES, PERMISSIONS.VIEW_SYSTEM_ACTIVITY],
};

export function hasPermission(role: UserRole, permission: Permission) {
  return rolePermissions[role].includes(permission);
}
